version: 2
jobs:
  build:
    working_directory: github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
    machine:
      enabled: true
    environment:
      GO15VENDOREXPERIMENT: 1
    branches:
      only:
        - master
    steps:
      - checkout

      - run: echo 'export GOPATH_HEAD="$(echo GOPATH|cut -d ':' -f 1)"' >> $BASH_ENV
      - run: echo 'export GOPATH_BASE="$GOPATH_HEAD/src/github.com/$CIRCLE_PROJECT_USERNAME"' >> $BASH_ENV
      - run: echo 'DOCKER_REPO="$(if [ $CIRCLE_PROJECT_USERNAME == 'Securing-DevOps' ]; then echo securingdevops; else echo $DOCKER_USER; fi)"' >> $BASH_ENV
      - run: mkdir -p "$GOPATH_BASE"
      - run: mkdir -p "$GOPATH_HEAD/bin"
      - run: ln -fs ${HOME}/${CIRCLE_PROJECT_REPONAME} ${GOPATH_BASE}/
          
          
          
      - run:
          name: Testing application
          command: >
            go test
            github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
            echo ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
            go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
            mkdir bin
            cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer
            docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .
            docker images --no-trunc | awk '/^app/ {print $3}' | tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt
            docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}
            
